void preencheCliente(TItemCliente *, int , int);
void saidaCliente(TItemCliente *, int);
int tempoAtendimentoCliente(TItemCliente *);
void adicionaDoisClientesNaFila(TFila *, int *, int *);
void entraNaFila(TItemCliente, TFila *);
void saiDaFila(TFila *, TItemCliente *);
int pilhaBandejasVazia(TPilha);
int pilhaBandejasCheia(TPilha);
void preencheBandeja(TItemBandeja *, int);
void retiraBandeja(TPilha *, TItemBandeja *);
void adicionaBandeja(TPilha *, TItemBandeja *, int *);
void vaiParaPosicao(TFila *, TItemCliente *);
void saiDaPosicao(TItemCliente, TFila *);
void preenchePosicaoVazio(TItemCliente *);
int posicaoVazia(TItemCliente);
void trocaFilas(TFila *, TFila *);
